packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": 24.5.0
  "@types/jest": 30.0.0
  jest: 30.1.3
  typescript: 5.9.2

injectWorkspacePackages: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - argon2
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
