const TOKEN_TTL_MINUTES = Number(
  process.env.PASSWORD_RESET_TOKEN_TTL_MINUTES ?? 30,
);
export const PASSWORD_RESET_TOKEN_TTL_MS = TOKEN_TTL_MINUTES * 60 * 1000;

const COOLDOWN_SECONDS = Number(
  process.env.PASSWORD_RESET_COOLDOWN_SECONDS ?? 60,
);
export const PASSWORD_RESET_COOLDOWN_MS = COOLDOWN_SECONDS * 1000;
